/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package filelocker.ui;


import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import java.io.FileNotFoundException;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.filechooser.FileSystemView;
import sun.awt.shell.ShellFolder;


/**
 *
 * @author i3-chathu-L
 */
public class GUIFileItem extends javax.swing.JPanel {



    
    private boolean isFileSelected;
    private final File currentFile;
    private final FileOperationListener fileOperationListener;
    /**
     * Creates new form GUIFileItem
     * @param file
     * @param fileOperationListener
     */
    public GUIFileItem(File file, FileOperationListener fileOperationListener) {
        initComponents();
        
        this.currentFile = file;
        this.fileOperationListener = fileOperationListener;
        
        setOpaque(true);

        lblFileIcon.setText(file.getName());

        
        
        try {
            ShellFolder sf = ShellFolder.getShellFolder(file);
            ImageIcon icon = new ImageIcon(sf.getIcon(true));                       
            lblFileIcon.setIcon(icon);

        } catch (FileNotFoundException ex) {
            Icon icon = FileSystemView.getFileSystemView().getSystemIcon(file);//new File("E:/HIDE.rar"));
            lblFileIcon.setIcon(icon);
        }       

        

        
        this.addMouseListener(new MouseAdapter() {

            @Override
            public void mouseClicked(MouseEvent e){
                if(currentFile.isDirectory() && e.getClickCount() == 2){
                    fileOperationListener.fileOpenOperationRequested(GUIFileItem.this);
                }else if(e.getClickCount() == 1){
                    fileOperationListener.clearFileSelectionOperationRequested();
                    setSelectedUI();
                    GUIFileItem.this.isFileSelected = true;
                }
            }
            
            @Override
            public void mousePressed(MouseEvent e){
                if(e.getButton() == MouseEvent.BUTTON3){
                    fileOperationListener.clearFileSelectionOperationRequested();
                    setSelectedUI();
                    GUIFileItem.this.isFileSelected = true;
                }
            }
            
            @Override
            public void mouseEntered(MouseEvent e) {
                
                if(!isFileSelected){
                    setHoverUI();
                }
            }

            @Override
            public void mouseExited(MouseEvent e) {
                if(!isFileSelected){
                    setDefaultUI();                    
                }

            }
        });
        
    }
    
    private void setHoverUI(){
        setBackground(new Color(0xd9, 0xef, 0xff));
    }
    private void setDefaultUI(){
        setBackground(null);
    }
    

    private void setSelectedUI(){
        setBackground(new Color(0x4c, 0xb0, 0xf7));        
    }
    
    public File getFile(){
        return currentFile;
    }
    
    public void deselectFile(){
        setDefaultUI();
        this.isFileSelected = false;
    }
    public boolean isFileSelected(){
        return isFileSelected;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rightClickContextMenu = new javax.swing.JPopupMenu();
        rccMenuItemEncrypt = new javax.swing.JMenuItem();
        rccMenuItemDecrypt = new javax.swing.JMenuItem();
        lblFileIcon = new javax.swing.JLabel();

        rccMenuItemEncrypt.setText("Lock");
        rccMenuItemEncrypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rccMenuItemEncryptActionPerformed(evt);
            }
        });
        rightClickContextMenu.add(rccMenuItemEncrypt);

        rccMenuItemDecrypt.setText("Unlock");
        rccMenuItemDecrypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rccMenuItemDecryptActionPerformed(evt);
            }
        });
        rightClickContextMenu.add(rccMenuItemDecrypt);

        setComponentPopupMenu(rightClickContextMenu);

        lblFileIcon.setBackground(new java.awt.Color(255, 204, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblFileIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblFileIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void rccMenuItemDecryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rccMenuItemDecryptActionPerformed
        // TODO add your handling code here:
        
        fileOperationListener.fileEncryptOrDecryptOperationRequested(FileOperationListener.FileEncryptOrDecryptOperation.DecryptOperation);
    }//GEN-LAST:event_rccMenuItemDecryptActionPerformed

    private void rccMenuItemEncryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rccMenuItemEncryptActionPerformed
        // TODO add your handling code here:
        fileOperationListener.fileEncryptOrDecryptOperationRequested(FileOperationListener.FileEncryptOrDecryptOperation.EncryptOperation);
    }//GEN-LAST:event_rccMenuItemEncryptActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblFileIcon;
    private javax.swing.JMenuItem rccMenuItemDecrypt;
    private javax.swing.JMenuItem rccMenuItemEncrypt;
    private javax.swing.JPopupMenu rightClickContextMenu;
    // End of variables declaration//GEN-END:variables
}
